# shellcheck shell=sh
# Steam app 1222700: generated by tools/umu2np.py from umu-protonfixes gamefixes-steam/1222700.py
# Source: https://github.com/Open-Wine-Components/umu-protonfixes/blob/f84287168e3ec4107131893c63cae76f66ea5011/gamefixes-steam/1222700.py
# Upstream commit: f84287168e3ec4107131893c63cae76f66ea5011
# Licence: BSD-2-Clause, Copyright (c) 2018, Chris Simons (umu-protonfixes);
#          full text in autofix/NOTICE.umu-protonfixes
# Translation: full (mapped 1, todo 0, n/a 0). Do not edit; put local changes in fixes/1222700.sh.

# umu: Work around UE4 OpenSSL crash on Intel 10th-gen and newer CPUs.
set_env OPENSSL_ia32cap ':~0x20000000'
