# shellcheck shell=sh
# Steam app 1361210: generated by tools/umu2np.py from umu-protonfixes gamefixes-steam/1361210.py
# Source: https://github.com/Open-Wine-Components/umu-protonfixes/blob/f84287168e3ec4107131893c63cae76f66ea5011/gamefixes-steam/1361210.py
# Upstream commit: f84287168e3ec4107131893c63cae76f66ea5011
# Licence: BSD-2-Clause, Copyright (c) 2018, Chris Simons (umu-protonfixes);
#          full text in autofix/NOTICE.umu-protonfixes
# Translation: full (mapped 2, todo 0, n/a 0). Do not edit; put local changes in fixes/1361210.sh.

# umu: Bypass the launcher to prevent bug: the game would launch as a background process with audio only.
replace_exe launcher/Launcher.exe binaries/Darktide.exe
# umu appends '-eac-untrusted --bundle-dir ../bundle --ini settings' as one argument; split into words here
append_arg -eac-untrusted
append_arg --bundle-dir
append_arg ../bundle
append_arg --ini
append_arg settings
