# shellcheck shell=sh
# Steam app 1467450: generated by tools/umu2np.py from umu-protonfixes gamefixes-steam/1467450.py
# Source: https://github.com/Open-Wine-Components/umu-protonfixes/blob/f84287168e3ec4107131893c63cae76f66ea5011/gamefixes-steam/1467450.py
# Upstream commit: f84287168e3ec4107131893c63cae76f66ea5011
# Licence: BSD-2-Clause, Copyright (c) 2018, Chris Simons (umu-protonfixes);
#          full text in autofix/NOTICE.umu-protonfixes
# Translation: partial (mapped 3, todo 2, n/a 1). Do not edit; put local changes in fixes/1467450.sh.
# Upstream file is a symlink to 65540.py

# TODO(umu): local helper set_resolution() not translated: set_resolution()
# TODO(umu): unsupported verb directmusic (not in autofix/verbs.json)
dll_override '*dsound' builtin
# n/a: set_env PULSE_LATENCY_MSEC 90 - Linux/Proton-only
dll_override ddraw native,builtin
dll_override dinput native,builtin
