# shellcheck shell=sh
# Steam app 15130: generated by tools/umu2np.py from umu-protonfixes gamefixes-steam/15130.py
# Source: https://github.com/Open-Wine-Components/umu-protonfixes/blob/f84287168e3ec4107131893c63cae76f66ea5011/gamefixes-steam/15130.py
# Upstream commit: f84287168e3ec4107131893c63cae76f66ea5011
# Licence: BSD-2-Clause, Copyright (c) 2018, Chris Simons (umu-protonfixes);
#          full text in autofix/NOTICE.umu-protonfixes
# Translation: partial (mapped 3, todo 2, n/a 1). Do not edit; put local changes in fixes/15130.sh.

# umu: Installs dsound d3dx9 arial d3dcompiler_47
# TODO(umu): unsupported verb dsound (not in autofix/verbs.json)
np_verb d3dx9
# TODO(umu): unsupported verb arial (not in autofix/verbs.json)
np_verb d3dcompiler_47
# n/a: regedit_add 'HKLM\Software\Wow6432Node\Ubisoft' - creates an empty key only, set_reg creates keys on demand
set_reg 'HKLM\Software\Wow6432Node\Ubisoft\Beyond Good & Evil' InstallLanguage REG_DWORD 1
