# shellcheck shell=sh
# Steam app 2138710: generated by tools/umu2np.py from umu-protonfixes gamefixes-steam/2138710.py
# Source: https://github.com/Open-Wine-Components/umu-protonfixes/blob/f84287168e3ec4107131893c63cae76f66ea5011/gamefixes-steam/2138710.py
# Upstream commit: f84287168e3ec4107131893c63cae76f66ea5011
# Licence: BSD-2-Clause, Copyright (c) 2018, Chris Simons (umu-protonfixes);
#          full text in autofix/NOTICE.umu-protonfixes
# Translation: partial (mapped 1, todo 1, n/a 0). Do not edit; put local changes in fixes/2138710.sh.

# umu: Stops the game from freezing.
# TODO(umu): set_ini_options is section-aware and adds missing keys; edit_file only rewrites existing "key=value" lines in AppData/Local/Sifu/Saved/Config/WindowsClient/Engine.ini
edit_file AppData/Local/Sifu/Saved/Config/WindowsClient/Engine.ini r.CreateShadersOnLoad 1
